version: '3'

services:
  my-tor-proxy:
    build: .
    restart: always
    container_name: my-tor-proxy
    ports:
      - "9050:9050"
    tty: true
#    volumes:
#      - ./torrc:/etc/tor/torrc
#    network_mode: host

    networks:
      my-tor-proxy:
        ipv4_address: 10.248.248.2

networks:
   my-tor-proxy:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.248.248.0/24



#volumes:
#   data-ache:
