version: '3'

services:
  tor-proxy:
    image: chanwitkepha/tor-proxy:alphine-3.19.1-20240511-0730
#    build: .
    restart: always
    container_name: tor-proxy
    ports:
      - "9050:9050"
    tty: true
#    volumes:
#      - ./torrc:/etc/tor/torrc
#    network_mode: host

    networks:
      tor-proxy:
        ipv4_address: 10.248.248.2

networks:
   tor-proxy:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.248.248.0/24

